# Generated by Django 6.0.3 on 2026-04-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('api_key_value', models.CharField(blank=True, max_length=100, null=True)),
                ('request_type', models.CharField(choices=[('STT', 'Voice-to-Text'), ('TTS', 'Text-to-Voice'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
