# Generated by Django 6.0.3 on 2026-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_audioasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioasset',
            name='developer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
