# Generated by Django 6.0.3 on 2026-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audioasset_developer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
