# Generated by Django 6.0.3 on 2026-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_developer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
